name: Events Repository
description: Manage events within a repository
author: deniz.blue

branding:
  icon: calendar
  color: yellow

inputs:
  events-path:
    description: The root folder where events are stored
    required: true
    default: "./events"

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node24
  main: dist/index.js
